apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: api
spec:
  ports:
  - name: default
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    group: com.redhat.training
    project: openshift-karaf-solution
    provider: fabric8
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
