package com.redhat.training.routes;

import org.apache.camel.builder.RouteBuilder;

public class OrderRouteBuilder extends RouteBuilder {

	@Override
	public void configure() throws Exception {
		
		//TODO read classes from the com.redhat.training.model package for JAXB
		
		//TODO Read only orders with the following file name: orders-v1-.*.csv"

		from("direct:process")
			.routeId("CommonProcessing")
			.onCompletion()
				.bean("performance", "stop")
			.end()
			//TODO Call the processor named assignBatch configured in jboss-camel-context.xml
			.bean("performance", "start")
			//TODO log each batch number to the console
			//TODO Convert each exchange to a Order object using Bindy
			//TODO split the list of orders to a single order
			//TODO Call order bean to update the order state and add the origin file name
			//TODO use a wiretap for auditing purposes
			//TODO Convert to XML using JAXB
			//TODO generate the file using the generateRandomFileName method from the order bean.
			.to("seda:audit")
			;
		
		from("seda:audit")
			.routeId("Audit")
			//TODO Aggregate orders based on the batchNumber that was provided by the assignBatch processor
			//TODO aggregate all the order after two seconds.
			//TODO update the file name that will be generated by this aggregation
			.choice()
				.when(xpath("number(/batch/@total) > 100"))
				//TODO if the total batch is over US$ 100 than save to /tmp/audit/large
				.otherwise()
				//TODO if the total batch is under US$ 100 than save to /tmp/audit/small
			.end()
			;
	}

}
